### PR TITLE
merge-sort/merge_sort.py

### PR DESCRIPTION
**Pull request by dmoneyballer**
An implementation of merge sort in Python3

### CODE REVIEW

**Comment by oznakn** [comment]
Please save file as _merge_sort.py_ in _merge-sort_ directory.

**Comment by oznakn** [comment]
Also, thanks for your contribution.

**Comment by dmoneyballer** [comment]
Does this fix it?

**Comment by oznakn** [comment]
Actually, probably the best thing to do closing this pr and reopening another. Otherwise, the merge-sort file will keep staying in the commit history and that is not something I want. Thanks again :blush:

**Pull request closed without merging**
